/**
 * One-time sheet builder. Menu: Avenues > Set up sheet (first time).
 *
 * Creates the seven tabs, fills them with what is currently live on the site,
 * and applies the header formatting and dropdowns. Running it again REPLACES
 * the contents of those tabs, so it is safe to re-run before anyone has made
 * edits and destructive afterwards — it asks first.
 *
 * Generated by scripts/make-setup-gs.mjs from apps-script/seed/*.tsv.
 * Do not hand-edit; regenerate instead.
 */

var SEED = {
  settings: [
    ["key","value"],
    ["applications_open","TRUE"],
    ["application_season","Fall 2026"],
    ["application_form_url","https://docs.google.com/forms/d/e/1FAIpQLSeGS66fNBZpsHZDOsy5rBiL4DSNfZH2ptiZibRGzTj8AyDfew/viewform"],
    ["members_password","as26"]
  ],
  team: [
    ["section","name","role","photo","linkedin"],
    ["executive","Armani C.","Co-President","armani","https://www.linkedin.com/in/armanichoy/"],
    ["executive","Calissa W.","Co-President","calissa","https://www.linkedin.com/in/calissa-welborn-usc/"],
    ["directors","Nate B.","Human Resources","nate","https://www.linkedin.com/in/nathan-brigger-019874304"],
    ["directors","Varenya S.","Finance","varenya","https://www.linkedin.com/in/varenya-sharma/"],
    ["directors","Grace L.","Recruitment","grace","https://www.linkedin.com/in/gr4lee"],
    ["directors","Vicky Z.","Recruitment","vicky","https://www.linkedin.com/in/vicky--zhang/"],
    ["directors","Sam B.","External Affairs","sam","https://www.linkedin.com/in/samiddhbiswas/"],
    ["directors","Mistie Z.","Internal Affairs","mistie","https://www.linkedin.com/in/mistiezheng/"],
    ["directors","Katherine Y.","Media & Marketing","katherine","https://www.linkedin.com/in/27katherineyu/"],
    ["directors","Ariana A.","Technology","ariana","https://www.linkedin.com/in/ariana-amiri"],
    ["directors","Darius M.","Alumni Engagement","darius","https://www.linkedin.com/in/darius-mahjoob"],
    ["directors","Anna C.","Alumni Engagement","anna","https://www.linkedin.com/in/annachi-usc"],
    ["associates","Rena J.","Human Resources","rena","https://www.linkedin.com/in/renajeoung/"],
    ["associates","Akshay M.","Finance","akhsay","https://www.linkedin.com/in/akshay-mediwala/"],
    ["associates","Akash P.","Recruitment","akash","https://www.linkedin.com/in/akashparikh228/"],
    ["associates","Samarth R.","Recruitment","samarth","https://www.linkedin.com/in/samarth-r/"],
    ["associates","Cici H.","External Affairs","cici","https://www.linkedin.com/in/xi-li-he"],
    ["associates","Chetan K.","External Affairs","chethan","https://www.linkedin.com/in/chetankurkure/"],
    ["associates","Cherim K.","Internal Affairs","cherim","https://www.linkedin.com/in/cherimki/"],
    ["associates","Nishitha P.","Internal Affairs","nishitha","https://www.linkedin.com/in/nishitha-pammidi"],
    ["associates","Vani S.","Media & Marketing","vani","https://www.linkedin.com/in/vani-sharma-926738290/"],
    ["associates","Cynthia S.","Media & Marketing","cynthia","https://www.linkedin.com/in/xinqishao/"],
    ["associates","Allison L.","Technology","allison","https://www.linkedin.com/in/allisonlin9"]
  ],
  mentors: [
    ["name","logo"],
    ["Accenture","accenture.png"],
    ["Bain & Company","bain.jpg"],
    ["BCG","bcg.png"],
    ["KPMG","kpmg.png"],
    ["Grata","grata.png"],
    ["EY","ey.png"],
    ["Deloitte","deloitte.png"]
  ],
  alumni: [
    ["company","logo","positions"],
    ["Bank of America","bank-of-america-emblem.png","Full-Time · PM"],
    ["EY","ey.png","Intern · Process & Controls"],
    ["JP Morgan","jp.png","Intern · IB, Intern · Analyst"],
    ["PwC","pwc.png","Intern · Cyber Defense & Eng., Intern · Cyber Risk & Reg., Intern · Tech Consultant"],
    ["Northrop Grumman","northrop.png","Intern · Cyber Info Assurance"],
    ["Deloitte","deloitte.png","Intern · Management Consulting"],
    ["Disney","disney.jpg","Intern · Corp. Enterprise Risk Mgmt."],
    ["KPMG","kpmg.png","Intern · Consultant"],
    ["General Dynamics","general_dynamics.jpg","Intern · Software Eng."],
    ["DrFirst","drfirst.png","Intern · Software Eng."],
    ["US Bank","usbank.png","Intern · PM"],
    ["Accenture","accenture.png","Intern · Consulting Analyst"]
  ],
  clients: [
    ["name","logo","services"],
    ["LinkedIn","linked.svg","Business Strategy"],
    ["AANC","aanc.png","Design, Technology"],
    ["DoorDash","doordash-logo.png","Business Strategy"],
    ["GALLA Beauty","galla.jpeg","Business Strategy"],
    ["Mountain Dew","mountain_dew_logo.svg.png","Business Strategy, Design"],
    ["Wheel & Tire Connection","wtc.jpeg","Business Strategy, Technology"],
    ["XP League","xp.jpg","Business Strategy"],
    ["Maryland STEM Festival","maryland.jpg","Marketing"],
    ["Network of Care","noc.png","Marketing, Design, Technology"],
    ["Captis Intelligence","captis.jpeg","Marketing, Design, Technology"]
  ],
  majors: [
    ["major"],
    ["Business Admin"],
    ["Computer Science"],
    ["Economics"],
    ["Art History"],
    ["Intelligence & Cyber Ops"],
    ["Public Policy"],
    ["Jazz Studies"],
    ["Real Estate"],
    ["Design"],
    ["BioPharm Marketing"],
    ["Financial Math"],
    ["Health Promotion"],
    ["Architecture"],
    ["Data Science"],
    ["Quant Bio"],
    ["Philosophy Politics & Econ"],
    ["Global Health"],
    ["Sociology"],
    ["Environmental Engineering"],
    ["International Relations"],
    ["Political Science"],
    ["Political Economy"],
    ["BioPharm Science"],
    ["Tech Design & Business"]
  ],
  faq: [
    ["question","answer"],
    ["When can I apply?","Avenues accepts new members at the start of each semester. Applications open during the first two weeks of the fall and spring semesters. Follow our Instagram @uscavenues for announcements on exact dates."],
    ["Is prior consulting or business experience required?","Not at all. We welcome students from all majors and backgrounds. What we look for is curiosity, a collaborative mindset, and a genuine desire to learn, not a polished resume."],
    ["What does the application process look like?","The process typically includes a written application followed by a brief interview. We want to learn about you, your interests, and how you think, not just your credentials."],
    ["How much time does membership require?","Expect to commit roughly 4–6 hours per week across client project work, org events, and curriculum nights. It's designed to be manageable alongside a full course load."],
    ["Can first-year and transfer students apply?","Yes, absolutely. We actively encourage first-years and transfers to apply. Many of our current leaders joined in their first semester at USC."],
    ["What happens if I'm not accepted?","We encourage you to reapply the following semester. Many members were not accepted on their first try. In the meantime, attend our open events to connect with the org and get a feel for what we do."]
  ],
};

var TAB_ORDER = ["settings","team","mentors","alumni","clients","majors","faq"];

/** Column widths, so the sheet is readable the moment it opens. */
var WIDTHS = {
  settings: [220, 520],
  team: [110, 170, 230, 130, 400],
  mentors: [220, 230],
  alumni: [220, 260, 320],
  clients: [190, 230, 320],
  majors: [260],
  faq: [400, 700],
};

function setUpSheet() {
  var ui = SpreadsheetApp.getUi();
  var ss = SpreadsheetApp.getActive();

  var existing = TAB_ORDER.filter(function (t) {
    return ss.getSheetByName(t) !== null;
  });
  if (existing.length) {
    var answer = ui.alert(
      'Replace existing tabs?',
      'This will overwrite: ' + existing.join(', ') +
        '\n\nAny edits in those tabs are lost. Continue?',
      ui.ButtonSet.YES_NO
    );
    if (answer !== ui.Button.YES) return;
  }

  TAB_ORDER.forEach(function (name) {
    var sheet = ss.getSheetByName(name);
    if (sheet) {
      sheet.clear();
      sheet.clearDataValidations();
    } else {
      sheet = ss.insertSheet(name);
    }
    var data = SEED[name];
    sheet.getRange(1, 1, data.length, data[0].length).setValues(data);

    // header row: dark, bold, frozen so it cannot scroll away
    var header = sheet.getRange(1, 1, 1, data[0].length);
    header.setFontWeight('bold').setFontColor('#ffffff').setBackground('#1f2937');
    sheet.setFrozenRows(1);

    (WIDTHS[name] || []).forEach(function (w, i) {
      sheet.setColumnWidth(i + 1, w);
    });
    if (name === 'faq') {
      sheet.getRange(2, 1, Math.max(sheet.getMaxRows() - 1, 1), 2).setWrap(true);
    }
  });

  // section dropdown — a typo here silently drops someone off the site
  var team = ss.getSheetByName('team');
  team
    .getRange(2, 1, Math.max(team.getMaxRows() - 1, 1), 1)
    .setDataValidation(
      SpreadsheetApp.newDataValidation()
        .requireValueInList(['executive', 'directors', 'associates'], true)
        .setAllowInvalid(false)
        .setHelpText('Must be executive, directors, or associates.')
        .build()
    );

  // applications_open must be a real boolean
  var settings = ss.getSheetByName('settings');
  var keys = settings.getRange(1, 1, settings.getLastRow(), 1).getValues();
  for (var i = 0; i < keys.length; i++) {
    if (String(keys[i][0]).trim() === 'applications_open') {
      settings
        .getRange(i + 1, 2)
        .setDataValidation(
          SpreadsheetApp.newDataValidation()
            .requireValueInList(['TRUE', 'FALSE'], true)
            .setAllowInvalid(false)
            .build()
        );
    }
  }

  // drop Google's default empty "Sheet1" if it is still lying around
  var leftover = ss.getSheetByName('Sheet1');
  if (leftover && ss.getSheets().length > 1) ss.deleteSheet(leftover);

  TAB_ORDER.forEach(function (name, i) {
    ss.setActiveSheet(ss.getSheetByName(name));
    ss.moveActiveSheet(i + 1);
  });
  ss.setActiveSheet(ss.getSheetByName('team'));

  ui.alert(
    'Sheet ready',
    'Created ' + TAB_ORDER.length + ' tabs with the content currently on the site.\n\n' +
      'Next: add your GitHub token under Project Settings > Script Properties as ' +
      'GITHUB_TOKEN, then run Avenues > Check for problems.',
    ui.ButtonSet.OK
  );
}
